language: python
python:
  - "2.7"
  - "3.4"
sudo: false
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gcc
    - gfortran
# command to install dependencies
install: 
  - "pip install --upgrade pip" 
  - "pip install -r requirements/python2.txt"
# command to run tests
script: python PyFin/tests/testSuite.py