language: python
python:
  - "2.7"
  - "3.4"
sudo: false
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gcc
    - gfortran
# command to install dependencies
install: 
  - "travis_wait pip install --upgrade pip"
  - "travis_wait pip install -r requirements.txt"
# command to run tests
script: 
  - "python setup.py build_ext --inplace"
  - "python PyFin/tests/testSuite.py"