dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
sudo: false
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gcc
    - gfortran
# command to install dependencies
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install numpy
  - conda install scipy
  - conda install pandas
  - conda install cython
  - pip install simpleutils
  - pip install coverage==4.5.4
  - pip install coveralls
# command to run tests
script:
  - python setup.py build_ext --line_trace --inplace
  - coverage run --omit test*.py --rcfile=./.coveragerc PyFin/tests/testSuite.py
  - coverage report --rcfile=./.coveragerc -i
  - coverage html --rcfile=./.coveragerc -i
after_success:
  - coveralls
