language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libblas-dev liblapack-dev
  - sudo apt-get install -qq gcc
  - sudo apt-get install -qq gfortran
# command to install dependencies
install: 
  - "pip install --upgrade pip" 
  - "pip install -r requirements/python2.txt"
# command to run tests
script: python setup.py test